### ISSUE TITLE
TS typings: getCookie has required argument "initialValue"?

### ISSUE THREAD

**Issue by jorundoa** [tylerwolff/useCookie#14]
So I see from the Readme that getCookie can be used without the initialValue parameter. However when I try to use this in my TS project it complains about be not supplying the second parameter. Why is this?

**Comment by tylerwolff** [comment]
Ah this may have been from a recent change that was made to handle SSR. I'll look into this and see what I can do. Thanks for bringing it up!

**Comment by jorundoa** [comment]
Any update on this @tylerwolff ?

**Comment by tylerwolff** [comment]
Hey sorry, I will try to get to it today or tomorrow. Been really busy on some other projects. Feel free to make a PR if you need it sooner though and I'll merge it in

**Comment by tylerwolff** [comment]
@jorundoa Hey sorry about the delay but I just released v1.2.1 that should fix this issue. Let me know if it works for you.

**Comment by tylerwolff** [comment]
closing as this should be fixed. Feel free to re-open if it continues to be a problem
