### ISSUE TITLE
initialValue doesn't actually set cookie

### ISSUE THREAD

**Issue by zacheryph** [tylerwolff/useCookie#16]
I am not sure if this is by design or just overlooked?

`useCookie` allows an `initialValue` but.. the initialValue never actually gets set to the cookie. I would assume "use cookie with inital value of X" would set the value to X if its not set?

Maybe this is wording, and `defaultValue` is what I'm thinking / would be preferred?

Either way it seems odd to give a value (initial or default) for a _useCookie_, and it not actually touch said cookie at all?

**Comment by chpio** [comment]
Why would `useCookie` touch cookies? It's a **reading** function, i would never expect a *getter* to *set* something.

**Comment by zacheryph** [comment]
I don't see anything that implies `useCookie` is read only?  I just think its odd to accept an `initialValue` for a _cookie_ (which is persistent by nature) and ... it not persist.

`useState` has an initial value. _state_ in this case has a life time and scope of that component.

_cookies_ on the other hand, do not have the same life time or scope. It seems _really_ odd I can `useCookie` in one component, with one value. While at the same exact time, in another component, use the _same cookie_ with a completely different value.

Again, maybe this is by design. Though it should probably be articulated that _initial value_ is not in fact the initial _cookie_ value.

**Comment by chpio** [comment]
> It seems _really_ odd I can `useCookie` in one component, with one value. While at the same exact time, in another component, use the _same cookie_ with a completely different value.

yeah, but that's not related to this issue, see https://github.com/tylerwolff/useCookie/pull/15

**Comment by zacheryph** [comment]
thank you for proving my point. See https://codesandbox.io/s/silly-benz-nlo1l

even with that patch two components with two different initial values view the cookie as two different values _UNTIL_ being persisted _AS_ a cookie.

**Comment by tylerwolff** [comment]
Thanks for bringing this up. I think `initialValue` may be the wrong name for this field. Something like `defaultValue` or `fallbackValue` might describe it more accurately. My original thought for doing it this way was to make it simple as possible to read/use a value that should be persisted in cookies. By having an `initialValue` it removes the need to do a separate check for null, but maybe that's just a bad shortcut. Maybe there should not be an initialValue param at all.

Either way I'd be hesitant to add something to hook initialization that would cause side effects to the cookie. This should only be done explicitly through the set function. If you need to set an initial cookie i would suggest using `useEffect` on mount.

**Comment by zacheryph** [comment]
Closing as _by design_

**Comment by chpio** [comment]
> If you need to set an initial cookie i would suggest using `useEffect` on mount.

How would you do that? After https://github.com/tylerwolff/useCookie/pull/12#issuecomment-855934879 gets fixed and the `initialValue` is removed it would return `null` on the first render *in any case* and then read the cookie value and set it on a second render. You would need a way to detect both cases:
1. the first render = `null`?
2. there's no cookie = `undefined`?

**Comment by tylerwolff** [comment]
@chpio so just so I'm following correctly, the issue here is that when using SSR, it doesn't have access to cookies on first render so without a default value it will always return `null` initially. Then after hydration it'll either be the cookie value or `undefined`, right?

Couldn't you detect both cases by using double equals `==` or `!=` ?

**Comment by chpio** [comment]
> it doesn't have access to cookies on first render

yeah, you don't have a cookie on the server and you need to match that value on the client for hydration.

> without a default value it will always return `null` initially. Then after hydration it'll either be the cookie value or `undefined`, right?

yeap



> Couldn't you detect both cases by using double equals `==` or `!=` ? or if you're rendering it something like `{value || 'default'}`

i meant, that you need to distinguish between those cases, so that you're setting the cookie value only if there is no cookie, but not on (every) first render.

```ts
const [cookie, setCookie] = useCookie("mycookie");

useEffect(
  () => {
    if (cookie === undefined) {
      setCookie("42");
    }
  },
  [cookie],
)
```
